### ISSUE TITLE
Append state issue

### ISSUE THREAD

**Issue by songrotek** [miyosuda/async_deep_reinforce#2]
self.s_t1 = np.append(x_t1,self.s_t[:,:,0:3], axis = 2) is wrong
it should be
self.s_t1 = np.append(self.s_t[:,:,1:],x_t1, axis = 2)

**Comment by miyosuda** [comment]
@songrotek 
Ah thanks!! I'll fix

**Comment by miyosuda** [comment]
The fix is applied to master branch.
