### ISSUE TITLE
how to see the training progress graph?

### ISSUE THREAD

**Issue by mingwugmail** [miyosuda/async_deep_reinforce#20]
like this one:

https://github.com/miyosuda/async_deep_reinforce/blob/master/docs/graph_24h.png

which script I should use to generate such graph?

**Comment by babaktr** [comment]
Navigate to the async_deep_reinforce folder in your terminal and run ```tensorboard --logdir tmp/```.

**Comment by mingwugmail** [comment]
Thanks.  I tried that (I have the model trained).

But on TensorBoard, I only saw some network chart under "GRAPHS" tab, what's the navigation to see the training score chart as above? I clicked around, but didn't find it.

**Comment by babaktr** [comment]
Hmm.. do you have the tmp/a3c_log folder with some event-file in it?

**Comment by mingwugmail** [comment]
yes. The training has been done.

2247976  events.out.tfevents.1481586057.ubuntu1604

**Comment by babaktr** [comment]
Hmmm... Strange. Close the terminal window and open a new one. Navigate to the ```async_deep_reinforce``` folder and run ```tensorboard --logdir tmp/```. Note the output on the terminal. Does it say anything? Port number perhaps? If so, open a web browser and go to localhost:<port number>. If you still don't see any score chart, I dunno. 

Oh btw, make sure you actually _expand_ the score window.  I think it will say different things depending on your tensorflow version. Mine is 0.12 and says scalar. Below that - score. Clicking that done expands the window.

**Comment by mingwugmail** [comment]
Thank you!
yes need to click "score", and it then show the chart window.

that "score" is not obvious to be clickable at all.
