### ISSUE TITLE
About variable error.

### ISSUE THREAD

**Issue by Michi-123** [miyosuda/async_deep_reinforce#33]
Hello.
When I ran "a3c.py"  or "a3c_display.py" , I got error log bellow.

********
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.8.0 locally
Traceback (most recent call last):
  File "a3c.py", line 50, in <module>
    global_network = GameACLSTMNetwork(ACTION_SIZE, -1, device)
  File "/home/uchi/async_deep_reinforce/game_ac_network.py", line 218, in __init__
    self.W_lstm = tf.get_variable("BasicLSTMCell/Linear/Matrix")
  File "/home/uchi/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 988, in get_variable
    custom_getter=custom_getter)
  File "/home/uchi/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 890, in get_variable
    custom_getter=custom_getter)
  File "/home/uchi/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 348, in get_variable
    validate_shape=validate_shape)
  File "/home/uchi/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 333, in _true_getter
    caching_device=caching_device, validate_shape=validate_shape)
  File "/home/uchi/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 657, in _get_single_variable
    "VarScope?" % name)
ValueError: Variable net_-1/BasicLSTMCell/Linear/Matrix does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=None in VarScope?

********
How do I resolve this problem?

**Comment by miyosuda** [comment]
I've upgraded my code from TensorFlow r0.12 to r1.0 just now. (These error occurred TF r1.0 environment while my code used to use r0.12 env.) Could you try again?

**Comment by Michi-123** [comment]
Thank you for replying, but I got messages at 'git clone'. 

git clone git@github.com:miyosuda/async_deep_reinforce.git
Cloning into 'async_deep_reinforce'...
Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.

---------------------
git clone https://github.com/miyosuda/Arcade-Learning-Environment.git
is OK.

**Comment by Michi-123** [comment]
Thank you for replying. 
At the first, I couldn't get source with the command
  'git clone git@github.com:miyosuda/async_deep_reinforce.git'
but I could get with the green Download button on the web site.
(the new one is  'async_deep_reinforce-master' , isn't it )

And now, your program is really working!

**Comment by Michi-123** [comment]
I have another question. I want to try the other games,  so I rewrote ROM parameter in 'constants.py'. 
But I got the error message below.
-----------------------------------------------
...
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.8.0 locally
A.L.E: Arcade Learning Environment (version 0.5.1)
[Powered by Stella]
Use -help for help screen.
Game console created:
  ROM file:  ../roms/myrom/pinball.bin
  Cart Name: Video Pinball (1980) (Atari) (PAL) [p1][!]
  Cart MD5:  a2424c1a0c783d7585d701b1c71b5fdc
  Display Format:  AUTO-DETECT ==> PAL
  ROM Size:        4096
  Bankswitch Type: AUTO-DETECT ==> 4K

Running ROM file...
Random seed is 0
Segmentation fault (core dumped)
---------------------------------------------------------

When you have time, please give me some advice.

**Comment by kmcnayr** [comment]
Reference to Issue: #32 
This needs to be updated again per the latest release notes: https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md

I successfully ran a3c.py by substituting "kernel" for "weights" and "bias" for "biases"
