### ISSUE TITLE
I can't train with the other games.

### ISSUE THREAD

**Issue by Michi-123** [miyosuda/async_deep_reinforce#35]
I want to train with the other games, so I downloaded ROMs from the site of ATARI and rewrote ROM parameter in 'constants.py'.
But I got the error message below.

...
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.8.0 locally
A.L.E: Arcade Learning Environment (version 0.5.1)
[Powered by Stella]
Use -help for help screen.
Game console created:
ROM file: ../roms/myrom/pinball.bin
Cart Name: Video Pinball (1980) (Atari) (PAL) [p1][!]
Cart MD5: a2424c1a0c783d7585d701b1c71b5fdc
Display Format: AUTO-DETECT ==> PAL
ROM Size: 4096
Bankswitch Type: AUTO-DETECT ==> 4K

Running ROM file...
Random seed is 0
Segmentation fault (core dumped)

*****
I found the supported game list in
'Arcade-Learning-Environment/src/games/supported'

**Comment by Michi-123** [comment]
I could play one 'Breakout' game with 'ACTION_SIZE = 4'. 
I think the name of games affect to run.

**Comment by mthrok** [comment]
Here is the list of valid ROM file names
```
air_raid.bin
alien.bin
amidar.bin
assault.bin
asterix.bin
asteroids.bin
atlantis.bin
bank_heist.bin
battle_zone.bin
beam_rider.bin
berzerk.bin
bowling.bin
boxing.bin
breakout.bin
carnival.bin
centipede.bin
chopper_command.bin
crazy_climber.bin
defender.bin
demon_attack.bin
double_dunk.bin
elevator_action.bin
enduro.bin
fishing_derby.bin
freeway.bin
frostbite.bin
gopher.bin
gravitar.bin
hero.bin
ice_hockey.bin
jamesbond.bin
journey_escape.bin
kangaroo.bin
krull.bin
kung_fu_master.bin
montezuma_revenge.bin
ms_pacman.bin
name_this_game.bin
phoenix.bin
pitfall.bin
pong.bin
pooyan.bin
private_eye.bin
qbert.bin
riverraid.bin
road_runner.bin
robotank.bin
seaquest.bin
skiing.bin
solaris.bin
space_invaders.bin
star_gunner.bin
tennis.bin
time_pilot.bin
tutankham.bin
up_n_down.bin
venture.bin
video_pinball.bin
wizard_of_wor.bin
yars_revenge.bin
zaxxon.bin
```

**Comment by Michi-123** [comment]
Thanks.
So far , 
ROM = "pong.bin"                                 # action size = 3
ROM = "../roms/myrom/Centipede.bin" # action size >= 6
ROM = "../roms/myrom/Breakout.bin"   # action size = 4
is available.

video_pinball.bin
space_invaders.bin
is not available...

**Comment by mthrok** [comment]
https://groups.google.com/group/arcade-learning-environment/attach/10bc8e55829890/supported_roms.zip?part=0.1&authuser=0&view=1

**Comment by Michi-123** [comment]
How did you find this archive?
Anyway, thanks a lot!
